[package]
name = "zbus-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4.7"
endi = "1.1.0"

[dependencies.zbus]
path = ".."
default-features = false

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "dbus"
path = "fuzz_targets/dbus.rs"
test = false
doc = false
