//! Compile-only fixture: a downstream crate whose `zbus` Cargo dependency is renamed.
//!
//! The default `::zbus` path emitted by the macros does not resolve here, so everything must go
//! through the `crate` attribute escape hatch.

#![allow(dead_code)]

use my_zbus::{interface, proxy};

#[proxy(
    interface = "org.freedesktop.RenamedFixture",
    default_service = "org.freedesktop.RenamedFixture",
    default_path = "/org/freedesktop/RenamedFixture",
    crate = "my_zbus"
)]
trait Renamed {
    fn some_method(&self) -> my_zbus::Result<String>;

    #[zbus(no_reply)]
    fn no_reply_method(&self) -> my_zbus::Result<()>;

    #[zbus(property)]
    fn some_property(&self) -> my_zbus::Result<u32>;
}

struct RenamedIface;

// The `proxy` attribute exercises the nested `proxy` macro invocation generated by `interface`:
// the `crate` path must be forwarded to it.
#[interface(
    name = "org.freedesktop.RenamedFixtureIface",
    crate = "my_zbus",
    proxy(gen_blocking = true)
)]
impl RenamedIface {
    fn some_method(&self) -> String {
        "some".to_string()
    }

    #[zbus(property)]
    fn some_property(&self) -> u32 {
        42
    }

    #[zbus(property)]
    fn set_some_property(&mut self, value: u32) {
        let _ = value;
    }
}

#[derive(Debug, my_zbus::DBusError)]
#[zbus(prefix = "org.freedesktop.RenamedFixture", crate = "my_zbus")]
enum Error {
    SomeError,
}

// The wire derives through the renamed crate.
#[derive(my_zbus::Type)]
#[zbus(crate = "my_zbus::wire")]
struct Data {
    field: u32,
}
