use snakecase::ascii::to_snakecase;
use std::{
    error::Error,
    fmt::{Display, Formatter, Write},
    process::{Command, Stdio},
};

use zbus::{
    names::BusName,
    zvariant::{ObjectPath, Signature},
};
use zbus_xml::{Arg, ArgDirection, Interface};

#[deprecated(since = "5.4.0", note = "use `CodeGenerator::file_code` instead")]
pub fn write_interfaces(
    interfaces: &[Interface<'_>],
    standard_interfaces: &[Interface<'_>],
    service: Option<BusName<'_>>,
    path: Option<ObjectPath<'_>>,
    input_src: &str,
    cargo_bin_name: &str,
    cargo_bin_version: &str,
) -> Result<String, Box<dyn Error + 'static>> {
    let code = CodeGenerator::new()
        .with_service(service.as_ref())
        .with_path(path.as_ref())
        .with_format(true)
        .file_code(
            interfaces,
            standard_interfaces,
            input_src,
            cargo_bin_name,
            cargo_bin_version,
        )?;

    Ok(code)
}

/// Write a doc header, listing the included Interfaces and how the
/// code was generated.
fn write_doc_header<W: std::fmt::Write>(
    w: &mut W,
    interfaces: &[Interface<'_>],
    standard_interfaces: &[Interface<'_>],
    input_src: &str,
    cargo_bin_name: &str,
    cargo_bin_version: &str,
) -> std::fmt::Result {
    if let Some((first_iface, following_ifaces)) = interfaces.split_first() {
        if following_ifaces.is_empty() {
            writeln!(
                w,
                "//! # D-Bus interface proxy for: `{}`",
                first_iface.name()
            )?;
        } else {
            write!(
                w,
                "//! # D-Bus interface proxies for: `{}`",
                first_iface.name()
            )?;
            for iface in following_ifaces {
                write!(w, ", `{}`", iface.name())?;
            }
            writeln!(w)?;
        }
    }

    write!(
        w,
        "//!
         //! This code was generated by `{cargo_bin_name}` `{cargo_bin_version}` from D-Bus introspection data.
         //! Source: `{input_src}`.
         //!
         //! You may prefer to adapt it, instead of using it verbatim.
         //!
         //! More information can be found in the [Writing a client proxy] section of the zbus
         //! documentation.
         //!
        ",
    )?;

    if !standard_interfaces.is_empty() {
        write!(w,
            "//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
             //! following zbus API can be used:
             //!
            ")?;
        for iface in standard_interfaces {
            let idx = iface.name().rfind('.').unwrap() + 1;
            let name = &iface.name()[idx..];
            writeln!(w, "//! * [`zbus::fdo::{name}Proxy`]")?;
        }
        write!(
            w,
            "//!
             //! Consequently `{cargo_bin_name}` did not generate code for the above interfaces.
            ",
        )?;
    }

    write!(
        w,
        "//!
        //! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
        //! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
        use zbus::proxy;
        "
    )?;

    Ok(())
}

#[deprecated(since = "5.4.0", note = "use `CodeGenerator` instead")]
pub struct GenTrait<'i> {
    pub interface: &'i Interface<'i>,
    pub service: Option<&'i BusName<'i>>,
    pub path: Option<&'i ObjectPath<'i>>,
    pub format: bool,
}

#[allow(deprecated)]
impl Display for GenTrait<'_> {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        let code = CodeGenerator::new()
            .with_service(self.service)
            .with_path(self.path)
            .with_format(self.format)
            .interface_code(self.interface)?;

        write!(f, "{code}")
    }
}

/// Generates Rust code from D-Bus introspection data.
///
/// The generator is configured through the builder-style `with_*` methods; the code is then
/// produced by [`CodeGenerator::interface_code`] (a proxy trait for one interface) or
/// [`CodeGenerator::file_code`] (a complete source file).
#[derive(Debug, Default, Clone)]
pub struct CodeGenerator<'i> {
    service: Option<&'i BusName<'i>>,
    path: Option<&'i ObjectPath<'i>>,
    format: bool,
}

impl<'i> CodeGenerator<'i> {
    /// Create a code generator with the default configuration.
    ///
    /// No default service or path, no formatting.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the well-known service name, for the proxies' `default_service`.
    pub fn with_service(mut self, service: Option<&'i BusName<'i>>) -> Self {
        self.service = service;
        self
    }

    /// Set the object path, for the proxies' `default_path`.
    pub fn with_path(mut self, path: Option<&'i ObjectPath<'i>>) -> Self {
        self.path = path;
        self
    }

    /// Set whether the generated code is passed through `rustfmt`.
    ///
    /// If `rustfmt` fails or is not available, the unformatted code is returned instead.
    pub fn with_format(mut self, format: bool) -> Self {
        self.format = format;
        self
    }

    /// The well-known service name, if any.
    pub fn service(&self) -> Option<&'i BusName<'i>> {
        self.service
    }

    /// The object path, if any.
    pub fn path(&self) -> Option<&'i ObjectPath<'i>> {
        self.path
    }

    /// Whether the generated code is passed through `rustfmt`.
    pub fn format(&self) -> bool {
        self.format
    }

    /// Generate the code for `interface`: a proxy trait.
    pub fn interface_code(&self, interface: &Interface<'_>) -> Result<String, std::fmt::Error> {
        let mut code = String::new();
        self.write_interface(&mut code, interface)?;

        Ok(if self.format {
            format_generated_code(&code).unwrap_or(code)
        } else {
            code
        })
    }

    /// Generate a complete source file: a doc header followed by the code for `interfaces`.
    ///
    /// `standard_interfaces` are only mentioned in the header, as zbus provides their
    /// implementation; `input_src`, `cargo_bin_name` and `cargo_bin_version` document where
    /// the code came from.
    pub fn file_code(
        &self,
        interfaces: &[Interface<'_>],
        standard_interfaces: &[Interface<'_>],
        input_src: &str,
        cargo_bin_name: &str,
        cargo_bin_version: &str,
    ) -> Result<String, std::fmt::Error> {
        let mut code = String::new();
        write_doc_header(
            &mut code,
            interfaces,
            standard_interfaces,
            input_src,
            cargo_bin_name,
            cargo_bin_version,
        )?;
        for interface in interfaces {
            self.write_interface(&mut code, interface)?;
        }

        Ok(if self.format {
            format_generated_code(&code).unwrap_or(code)
        } else {
            code
        })
    }

    fn write_interface<W: Write>(&self, w: &mut W, iface: &Interface<'_>) -> std::fmt::Result {
        let idx = iface.name().rfind('.').unwrap() + 1;
        let name = &iface.name()[idx..];

        if let Some(docstring) = iface.docstring() {
            write_doc_lines(w, docstring, "")?;
        }
        write!(w, "#[proxy(interface = \"{}\"", iface.name())?;
        if let Some(service) = self.service {
            write!(w, ", default_service = \"{service}\"")?;
        }
        if let Some(path) = self.path {
            write!(w, ", default_path = \"{path}\"")?;
        }
        if self.path.is_none() || self.service.is_none() {
            write!(w, ", assume_defaults = true")?;
        }
        writeln!(w, ")]")?;
        writeln!(w, "pub trait {name} {{")?;

        let mut methods = iface.methods().to_vec();
        methods.sort_by(|a, b| a.name().partial_cmp(&b.name()).unwrap());
        for m in &methods {
            let (inputs, output) = inputs_output_from_args(m.args());
            let name = to_identifier(&to_snakecase(m.name().as_str()));
            writeln!(w)?;
            writeln!(w, "    /// {} method", m.name())?;
            write_member_docs(w, m.docstring(), m.args())?;
            if pascal_case(&name) != m.name().as_str() {
                writeln!(w, "    #[zbus(name = \"{}\")]", m.name())?;
            }
            hide_clippy_lints(w, m)?;
            writeln!(w, "    fn {name}({inputs}){output};")?;
        }

        let mut signals = iface.signals().to_vec();
        signals.sort_by(|a, b| a.name().partial_cmp(&b.name()).unwrap());
        for signal in &signals {
            let args = parse_signal_args(signal.args());
            let name = to_identifier(&to_snakecase(signal.name().as_str()));
            writeln!(w)?;
            writeln!(w, "    /// {} signal", signal.name())?;
            write_member_docs(w, signal.docstring(), signal.args())?;
            if pascal_case(&name) != signal.name().as_str() {
                writeln!(w, "    #[zbus(signal, name = \"{}\")]", signal.name())?;
            } else {
                writeln!(w, "    #[zbus(signal)]")?;
            }
            writeln!(w, "    fn {name}({args}) -> zbus::Result<()>;",)?;
        }

        let mut props = iface.properties().to_vec();
        props.sort_by(|a, b| a.name().partial_cmp(&b.name()).unwrap());
        for p in props {
            let name = to_identifier(&to_snakecase(p.name().as_str()));
            let fn_attribute = if pascal_case(&name) != p.name().as_str() {
                format!("    #[zbus(property, name = \"{}\")]", p.name())
            } else {
                "    #[zbus(property)]".to_string()
            };

            writeln!(w)?;
            writeln!(w, "    /// {} property", p.name())?;
            write_member_docs(w, p.docstring(), &[])?;
            if p.access().read() {
                writeln!(w, "{fn_attribute}")?;
                let output = to_rust_type(p.ty(), false, false);
                hide_clippy_type_complexity_lint(w, p.ty())?;
                writeln!(w, "    fn {name}(&self) -> zbus::Result<{output}>;",)?;
            }

            if p.access().write() {
                writeln!(w, "{fn_attribute}")?;
                let input = to_property_setter_type(p.ty());
                writeln!(
                    w,
                    "    fn set_{name}(&self, value: {input}) -> zbus::Result<()>;",
                )?;
            }
        }
        writeln!(w, "}}")
    }
}

/// Write a docstring (from the Telepathy introspection extensions) as rustdoc comment lines.
///
/// The content is typically HTML, which rustdoc passes through; only the indentation is
/// rewritten, as the original one is meaningless after the lines are prefixed with `///`.
fn write_doc_lines<W: Write>(w: &mut W, docstring: &str, indent: &str) -> std::fmt::Result {
    for line in doc_markdown(docstring).lines() {
        if line.is_empty() {
            writeln!(w, "{indent}///")?;
        } else {
            writeln!(w, "{indent}/// {line}")?;
        }
    }
    Ok(())
}

/// Convert a Telepathy docstring — an HTML fragment — into Markdown for a rustdoc comment.
///
/// The docstrings embedded by the Telepathy extensions are HTML (`<p>`, `<em>`, and their own
/// `<tp:rationale>`, …). Emitting them verbatim would leak the tags into the generated docs, so
/// they are converted: block-level tags become paragraph breaks (a blank line), `<em>`,
/// `<strong>` and `<code>` become their Markdown equivalents, any other tag is stripped, entity
/// references are resolved and insignificant HTML whitespace is collapsed. The result is a
/// sequence of single-line paragraphs separated by blank lines — so a bare carriage return
/// cannot survive into a doc comment either.
fn doc_markdown(docstring: &str) -> String {
    fn flush(paragraphs: &mut Vec<String>, current: &mut String) {
        let paragraph = current.split_whitespace().collect::<Vec<_>>().join(" ");
        current.clear();
        if !paragraph.is_empty() {
            paragraphs.push(paragraph);
        }
    }

    let mut paragraphs = Vec::new();
    let mut current = String::new();
    let mut rest = docstring;
    while let Some(open) = rest.find('<') {
        push_text(&mut current, &rest[..open]);
        rest = &rest[open..];

        // Comments, CDATA sections and processing instructions.
        if let Some(after) = rest.strip_prefix("<!--") {
            rest = after.split_once("-->").map_or("", |(_, after)| after);
            continue;
        }
        if let Some(after) = rest.strip_prefix("<![CDATA[") {
            let (cdata, after) = after.split_once("]]>").unwrap_or((after, ""));
            current.push_str(cdata); // CDATA content is literal text.
            rest = after;
            continue;
        }
        if rest.starts_with("<?") {
            rest = rest.split_once("?>").map_or("", |(_, after)| after);
            continue;
        }

        let Some(close) = rest.find('>') else {
            push_text(&mut current, rest);
            return finish(paragraphs, current);
        };
        let tag = &rest[1..close];
        rest = &rest[close + 1..];

        let name = tag
            .trim_start_matches('/')
            .split([' ', '\t', '\n', '\r', '/'])
            .next()
            .unwrap_or("");
        // Match on the local name, so a namespace prefix (e. g. `tp:`) doesn't matter.
        match name
            .rsplit(':')
            .next()
            .unwrap_or(name)
            .to_ascii_lowercase()
            .as_str()
        {
            "strong" | "b" => current.push_str("**"),
            "em" | "i" => current.push('*'),
            "code" | "tt" => current.push('`'),
            "p" | "br" | "div" | "blockquote" | "ul" | "ol" | "li" | "dl" | "dt" | "dd" | "pre"
            | "rationale" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" => {
                flush(&mut paragraphs, &mut current)
            }
            _ => {} // Strip any other tag.
        }
    }
    push_text(&mut current, rest);
    finish(paragraphs, current)
}

/// Join a docstring's paragraphs, flushing any final one.
fn finish(mut paragraphs: Vec<String>, current: String) -> String {
    let last = current.split_whitespace().collect::<Vec<_>>().join(" ");
    if !last.is_empty() {
        paragraphs.push(last);
    }
    paragraphs.join("\n\n")
}

/// Append `text` to `out`, resolving XML entity references (`&amp;`, `&#65;`, …).
fn push_text(out: &mut String, text: &str) {
    let mut rest = text;
    while let Some(amp) = rest.find('&') {
        out.push_str(&rest[..amp]);
        rest = &rest[amp..];
        match rest[1..]
            .split_once(';')
            .and_then(|(entity, after)| decode_entity(entity).map(|c| (c, after)))
        {
            Some((c, after)) => {
                out.push(c);
                rest = after;
            }
            // Not a recognized reference: keep the `&` literal.
            None => {
                out.push('&');
                rest = &rest[1..];
            }
        }
    }
    out.push_str(rest);
}

/// Resolve an XML entity reference (the part between `&` and `;`).
fn decode_entity(entity: &str) -> Option<char> {
    match entity {
        "amp" => return Some('&'),
        "lt" => return Some('<'),
        "gt" => return Some('>'),
        "quot" => return Some('"'),
        "apos" => return Some('\''),
        _ => {}
    }
    let code = match entity.strip_prefix('#') {
        Some(dec_or_hex) => match dec_or_hex.strip_prefix(['x', 'X']) {
            Some(hex) => u32::from_str_radix(hex, 16).ok()?,
            None => dec_or_hex.parse().ok()?,
        },
        None => return None,
    };
    char::from_u32(code)
}

/// Write the docstrings of an interface member and of its args, if any, as rustdoc comments.
fn write_member_docs<W: Write>(
    w: &mut W,
    docstring: Option<&str>,
    args: &[Arg],
) -> std::fmt::Result {
    if let Some(docstring) = docstring {
        writeln!(w, "    ///")?;
        write_doc_lines(w, docstring, "    ")?;
    }

    let mut wrote_header = false;
    for arg in args {
        let (Some(name), Some(docstring)) = (arg.name(), arg.docstring()) else {
            continue;
        };
        if !wrote_header {
            writeln!(w, "    ///")?;
            writeln!(w, "    /// # Arguments")?;
            writeln!(w, "    ///")?;
            wrote_header = true;
        }
        let markdown = doc_markdown(docstring);
        let mut lines = markdown.lines();
        writeln!(
            w,
            "    /// * `{}` - {}",
            to_identifier(name),
            lines.next().unwrap_or_default()
        )?;
        // Indent continuation lines so they stay part of the list item.
        for line in lines {
            if line.is_empty() {
                writeln!(w, "    ///")?;
            } else {
                writeln!(w, "    ///   {line}")?;
            }
        }
    }

    Ok(())
}

fn hide_clippy_lints<W: Write>(write: &mut W, method: &zbus_xml::Method<'_>) -> std::fmt::Result {
    // check for <https://rust-lang.github.io/rust-clippy/master/index.html#/too_many_arguments>
    // triggers when a functions has at least 7 paramters
    if method.args().len() >= 7 {
        writeln!(write, "    #[allow(clippy::too_many_arguments)]")?;
    }

    // check for <https://rust-lang.github.io/rust-clippy/master/index.html#/type_complexity>
    for arg in method.args() {
        let signature = arg.ty();
        hide_clippy_type_complexity_lint(write, signature)?;
    }

    Ok(())
}

fn hide_clippy_type_complexity_lint<W: Write>(
    write: &mut W,
    signature: &Signature,
) -> std::fmt::Result {
    let complexity = estimate_type_complexity(signature);
    if complexity >= 1700 {
        writeln!(write, "    #[allow(clippy::type_complexity)]")?;
    }
    Ok(())
}

fn inputs_output_from_args(args: &[Arg]) -> (String, String) {
    let mut inputs = vec!["&self".to_string()];
    let mut output: Vec<OutputArg> = vec![];
    let mut n = 0;
    let mut gen_name = || {
        n += 1;
        format!("arg_{n}")
    };

    for a in args {
        match a.direction() {
            None | Some(ArgDirection::In) => {
                let ty = to_rust_type(a.ty(), true, true);
                let arg = if let Some(name) = a.name() {
                    to_identifier(name)
                } else {
                    gen_name()
                };
                inputs.push(format!("{arg}: {ty}"));
            }
            Some(ArgDirection::Out) => {
                let ty = to_rust_type(a.ty(), false, false);
                let is_struct = matches!(a.ty().inner(), Signature::Structure(_));
                output.push(OutputArg { ty, is_struct });
            }
        }
    }

    let output_str = match &output[..] {
        [] => "()".to_string(),
        [
            OutputArg {
                ty,
                is_struct: true,
            },
        ] => {
            // If there's a single output argument and it is a struct type, we need to wrap it
            // in a tuple to distinguish it from multiple return values
            format!("({ty},)")
        }
        [
            OutputArg {
                ty,
                is_struct: false,
            },
        ] => ty.clone(),
        multiple => {
            let types = multiple
                .iter()
                .map(|arg| arg.ty.as_str())
                .collect::<Vec<_>>();
            format!("({})", types.join(", "))
        }
    };

    (inputs.join(", "), format!(" -> zbus::Result<{output_str}>"))
}

#[derive(Debug)]
struct OutputArg {
    ty: String,
    is_struct: bool,
}

fn parse_signal_args(args: &[Arg]) -> String {
    let mut inputs = vec!["&self".to_string()];
    let mut n = 0;
    let mut gen_name = || {
        n += 1;
        format!("arg_{n}")
    };

    for a in args {
        let ty = to_rust_type(a.ty(), true, false);
        let arg = if let Some(name) = a.name() {
            to_identifier(name)
        } else {
            gen_name()
        };
        inputs.push(format!("{arg}: {ty}"));
    }

    inputs.join(", ")
}

fn to_rust_type(ty: &Signature, input: bool, as_ref: bool) -> String {
    // can't haz recursive closure, yet
    fn signature_to_rust_type(signature: &Signature, input: bool, as_ref: bool) -> String {
        match signature {
            Signature::Unit => "".into(),
            Signature::U8 => "u8".into(),
            Signature::Bool => "bool".into(),
            Signature::I16 => "i16".into(),
            Signature::U16 => "u16".into(),
            Signature::I32 => "i32".into(),
            Signature::U32 => "u32".into(),
            Signature::I64 => "i64".into(),
            Signature::U64 => "u64".into(),
            Signature::F64 => "f64".into(),
            #[cfg(unix)]
            Signature::Fd if input => "zbus::zvariant::Fd<'_>".into(),
            #[cfg(unix)]
            Signature::Fd => "zbus::zvariant::OwnedFd".into(),
            Signature::Str if input || as_ref => "&str".into(),
            Signature::Str => "String".into(),
            Signature::ObjectPath if input => {
                if as_ref {
                    "&zbus::zvariant::ObjectPath<'_>".into()
                } else {
                    "zbus::zvariant::ObjectPath<'_>".into()
                }
            }
            Signature::ObjectPath => "zbus::zvariant::OwnedObjectPath".into(),
            Signature::Signature if input => {
                if as_ref {
                    "&zbus::zvariant::Signature<'_>".into()
                } else {
                    "zbus::zvariant::Signature<'_>".into()
                }
            }
            Signature::Signature => "zbus::zvariant::OwnedSignature".into(),
            Signature::Variant if input => {
                if as_ref {
                    "&zbus::zvariant::Value<'_>".into()
                } else {
                    "zbus::zvariant::Value<'_>".into()
                }
            }
            Signature::Variant => "zbus::zvariant::OwnedValue".into(),
            Signature::Array(child) => {
                let child_ty = signature_to_rust_type(child, input, as_ref);
                if input && as_ref {
                    format!("&[{child_ty}]")
                } else {
                    format!("Vec<{child_ty}>")
                }
            }
            Signature::Dict { key, value } => {
                let key_ty = signature_to_rust_type(key, input, as_ref);
                let value_ty = signature_to_rust_type(value, input, as_ref);

                format!("std::collections::HashMap<{key_ty}, {value_ty}>")
            }
            Signature::Structure(fields) => {
                let fields = fields
                    .iter()
                    .map(|f| signature_to_rust_type(f, input, as_ref))
                    .collect::<Vec<_>>();

                if fields.len() > 1 {
                    format!("{}({})", if as_ref { "&" } else { "" }, fields.join(", "))
                } else {
                    format!("{}({},)", if as_ref { "&" } else { "" }, fields[0])
                }
            }
            #[allow(unreachable_patterns)]
            _ => unreachable!("Unsupported signature: {}", signature),
        }
    }

    signature_to_rust_type(ty, input, as_ref)
}

// Like `to_rust_type` for an input parameter, but tailored to property setters.
//
// `Proxy::set_property` requires the value to satisfy `T: Into<Value<'t>>`. For most
// types, the `&T` form already implements this (via `From<&T> for Value`). For `Variant`
// and `Structure`, the `&T` form does not, so the owned form is emitted instead, also
// when these appear nested inside an `Array` or `Dict`.
fn to_property_setter_type(ty: &Signature) -> String {
    fn inner(signature: &Signature) -> String {
        match signature {
            Signature::Variant => "zbus::zvariant::Value<'_>".into(),
            Signature::Structure(fields) => {
                let fields = fields.iter().map(inner).collect::<Vec<_>>();
                if fields.len() > 1 {
                    format!("({})", fields.join(", "))
                } else {
                    format!("({},)", fields[0])
                }
            }
            Signature::Array(child) => format!("&[{}]", inner(child)),
            Signature::Dict { key, value } => {
                format!(
                    "std::collections::HashMap<{}, {}>",
                    inner(key),
                    inner(value),
                )
            }
            _ => to_rust_type(signature, true, true),
        }
    }
    inner(ty)
}

static KWORDS: &[&str] = &[
    "Self", "abstract", "as", "async", "await", "become", "box", "break", "const", "continue",
    "crate", "do", "dyn", "else", "enum", "extern", "false", "final", "fn", "for", "if", "impl",
    "in", "let", "loop", "macro", "match", "mod", "move", "mut", "override", "priv", "pub", "ref",
    "return", "self", "static", "struct", "super", "trait", "true", "try", "type", "typeof",
    "union", "unsafe", "unsized", "use", "virtual", "where", "while", "yield",
];

fn to_identifier(id: &str) -> String {
    if KWORDS.contains(&id) {
        format!("{id}_")
    } else {
        id.replace('-', "_")
    }
}

// This function is the same as zbus_macros::utils::pascal_case
pub fn pascal_case(s: &str) -> String {
    let mut pascal = String::new();
    let mut capitalize = true;
    for ch in s.chars() {
        if ch == '_' {
            capitalize = true;
        } else if capitalize {
            pascal.push(ch.to_ascii_uppercase());
            capitalize = false;
        } else {
            pascal.push(ch);
        }
    }
    pascal
}

fn estimate_type_complexity(signature: &Signature) -> u32 {
    let mut score = 0;

    match signature {
        Signature::Unit => (),
        Signature::U8
        | Signature::Bool
        | Signature::I16
        | Signature::U16
        | Signature::I32
        | Signature::U32
        | Signature::I64
        | Signature::U64
        | Signature::F64
        | Signature::Str => score += 1,
        #[cfg(unix)]
        Signature::Fd => score += 10,
        Signature::ObjectPath | Signature::Signature | Signature::Variant => score += 10,
        Signature::Array(child) => score += 5 * estimate_type_complexity(child),
        Signature::Dict { key, value } => {
            score *= 10 + 50;
            score += 5 * estimate_type_complexity(key);
            score += 5 * estimate_type_complexity(value);
        }
        Signature::Structure(fields) => {
            score += 50;
            for field in fields.iter() {
                score += 5 * estimate_type_complexity(field);
            }
        }
        #[allow(unreachable_patterns)]
        _ => unreachable!("Unsupported signature: {}", signature),
    }

    score
}

fn format_generated_code(generated_code: &str) -> std::io::Result<String> {
    use std::io::{Read, Write};

    let mut process = Command::new("rustfmt")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        // rustfmt may post warnings about features not being enabled on stable rust
        // these can be distracting and are irrevelant to the user, so we hide them
        .stderr(Stdio::null())
        .spawn()?;
    let rustfmt_stdin = process.stdin.as_mut().unwrap();
    let mut rustfmt_stdout = process.stdout.take().unwrap();
    writeln!(rustfmt_stdin)?;
    rustfmt_stdin.write_all(generated_code.as_bytes())?;

    let exit_status = process.wait()?;
    if !exit_status.success() {
        eprintln!("`rustfmt` did not exit successfully. Continuing with unformatted code.");
        return Ok(generated_code.to_string());
    }

    let mut formatted = String::new();
    rustfmt_stdout.read_to_string(&mut formatted)?;

    Ok(formatted)
}
